# Generated by Django 3.0 on 2020-07-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='content',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
