# Generated by Django 3.0 on 2020-07-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgl', '0004_hero_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='about',
            new_name='content',
        ),
    ]
